### PR TITLE
Enchancement rating range #2

### PR DESCRIPTION
**Pull request by menon123**
included a case for searching between a range including the upper and lower limit of the range.

### CODE REVIEW

**Comment by menon123** [comment]
Yes will do

**Comment by AyushmaanKaushik** [comment]
I'm coming across errors when I enter the lower and upper limit ranges. Please recheck the code and let me know.

**Comment by karunakc** [comment]
Hey! Looks good!

**Comment by karunakc** [comment]
!bounty 40

**Pull request closed without merging**
