### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by 21Dlexis**
I've fixed bugs I could find in the code; mainly:
1. Indentation errors
2. Incorrect input errors
3. Fuzzywuzzy function range error
4.  Minor code error

### CODE REVIEW

**Comment by AyushmaanKaushik** [comment]
Could you elaborate on what errors you came across in the code and how you've fixed them?

**Comment by AyushmaanKaushik** [comment]
Hey, nice work but some of the bug fixes still don't work. The author search function only seems to search up the last name of the author and the rating range gives me erros.

**Comment by 21Dlexis** [comment]
Could you let me know what error is coming up in the rating range?

**Comment by 21Dlexis** [comment]
I'm working on fixing those errors. Are the other bug fixes (2 and 3 )alright?

**Comment by AyushmaanKaushik** [comment]
Yes those are fine

**Comment by 21Dlexis** [comment]
I just put in statements informing the user in bug3, so I guess it isn't really a bug like you said. 
I've tried to resolve the previous errors Ayushmaan mentioned and committed that file now. Please do check it out and let me know.

**Comment by karunakc** [comment]
!bounty 60

**Comment by 21Dlexis** [comment]
Thank you!

**Pull request closed without merging**
