### PR TITLE
Fixed input validations for menu option 3

### PR DESCRIPTION
**Pull request by ishitabinz**
Validating the input for lower and upper limit
Slight changes in display

### CODE REVIEW

**Comment by karunakc** [comment]
Hey! Can you please elaborate more on your issues, thanks!

**Comment by ishitabinz** [comment]
I have added validations for inputs of lower value and upper value of rating range entered by user, to ensure numeric and valid values.

**Comment by karunakc** [comment]
Hey! The validation for the input range between 1 and 5 already exists! And considering that it wasn't an issue that was breaking the code, it cannot be accepted as a bug fix :)

**Comment by ishitabinz** [comment]
Oh, I was trying to account for non numeric inputs :( can that be considered?

**Comment by karunakc** [comment]
we can assign a minimum bounty points for that, thank you :)

**Pull request closed without merging**
